exclude: 'docs|node_modules|migrations|.git|.tox'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: check-yaml

- repo: https://github.com/psf/black
  rev: '22.1.0'
  hooks:
    - id: black
      args: [--line-length=120, --skip-string-normalization]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.0.0
  hooks:
    - id: reorder-python-imports

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      additional_dependencies: [
      'flake8-comprehensions',
      'flake8-deprecated',
      'flake8-mutable',
      'flake8-string-format',
      'flake8-tidy-imports']
      args: ['--config=setup.cfg', '--max-line-length=120', --extend-ignore=E203]

- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
    - id: pyupgrade

- repo: https://github.com/PyCQA/pylint
  rev: v2.12.2
  hooks:
    - id: pylint
      args: [--max-line-length=120, --disable=all, --enable=W0102, --enable= R1714, --enable=C0116,
      --enable= C0115, --enable=W0107, --enable=E1101, --enable=C0114]
